name: First-Job
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: first job
        run: |
          echo "Hi"
          ls        
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: |
          echo "second"
          ls
  third-job:
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: |
          echo "third" 
          ls
