name: First-Job
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: |
          echo "Hi"
          ls
          pwd
          echo "End"
